language: node_js

node_js:
  - "6.1"

before_install:
  - nvm install 7.1.0
  - nvm use 7.1.0
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - npm test

after_script:
  - npm run coverage

after_success:
  - npm run ci-publish || true