language: node_js

node_js:
  - "6.1"

before_script:
  - nvm install 7.1.0
  - nvm use 7.1.0
  - npm install

script:
  - npm test

after_script:
  - npm run coverage

after_success:
  - npm run ci-publish || true