language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

branches:
  only:
    - master
    - release

env:
  global:
    - secure: G87hR1MzHgI7dG49zIZjc+U1TP6Fi6qDiRF37+SLr3iXFpgonTLGYrrAi8qazAiD9z9210xpG+l0e6SLeSINK/al4Y/WlJve3liJoiFPuslRP2oKr3pKIlORayk9mzKxtSafLM7Nl98PxJCwTa9aOcZ6qCQ1vpidbB3EDXgsqlpDM+FD9cILKkZ3wXOR8izzQb+zt9BHp6Vz7cQAc2xiOGQvpBqNVlP0Y8VfxVbO/55oNEtPd/9bwCD54Zuro9nEPPdq1OUcm+A4Bls+Nq/jxgpuUkGYWcAD9PlbnwPGuzLZhfN1XuHvmkVl4fnHKay0wHbrlhfj/vuQ4rQnUyFNT02NxzsRu4wlqL1AFac8qBuV3RT9VhrWLNLna2HltkM/jusiTrm7HWhI+LtPpZVbSJJ9LdABdkFsf7Ff8XLG+ms2hl0KDRsR1D0HsNKjNSFLfhumSGfORCMs+DlAb2Vge63M/VieW8SvJJUfkgTVxAob/O0CNLRgVzhfzbvgWpjswkdTqUvQF/+AGhSFS/8z5IdHb1ao4SEystip/e774Tj0ZEaj/ARAcKdZPa4vb1A+ZhBzSdevGh6gwD4PFttXYdJR/4W7s95IbN/XnddopPYZkx+5WyiDqZJXognHPcl2uIvLqHIzEKbUOSMuh0r+ud6358Z9vY4hbvEFWFMVD78=

install:
  - yarn install

script:
  - if [ "$TRAVIS_BRANCH" = "release" ]; then npm run dist; fi
  - npm test

after_script:
  - npm run coverage

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: release
